#include "params.h"

// params
u64 ISO_FALPHA = 2;
/* All rates are in Mbps */
u64 ISO_MAX_TX_RATE = 10000;
// The VQ's net drain rate in Mbps is 90% of 10G ~ 9000 Mbps
u64 ISO_VQ_DRAIN_RATE_MBPS = 9000;
u64 ISO_MAX_BURST_TIME_US = 1000;
u64 ISO_MIN_BURST_BYTES = 1;
u64 ISO_RATEMEASURE_INTERVAL_US = 1000 * 100;
u64 ISO_TOKENBUCKET_TIMEOUT_NS = 1000 * 1000;
u64 ISO_TOKENBUCKET_MARK_THRESH_BYTES = 512 * 1024;
u64 ISO_TOKENBUCKET_DROP_THRESH_BYTES = 512 * 1024;
u64 ISO_VQ_MARK_THRESH_BYTES = 1024 * 1000;
u64 ISO_VQ_MAX_BYTES = 2048 * 1024;
u64 ISO_RFAIR_INITIAL = 100;
u64 ISO_MIN_RFAIR = 1;
u64 ISO_RFAIR_INCREMENT = 10;
u64 ISO_RFAIR_DECREASE_INTERVAL_US = 5000;
u64 ISO_RFAIR_INCREASE_INTERVAL_US = 5000;
u64 ISO_RFAIR_FEEDBACK_TIMEOUT_US = 1000 * 1000;
u64 ISO_RFAIR_FEEDBACK_TIMEOUT_DEFAULT_RATE = 10;
u64 IsoGlobalEnabled = 0;
u64 IsoEnablePortClassMap = 0;

// DEBUG: setting it to 666 means we will ALWAYS generate feedback for
// EVERY packet!
// USE IT ONLY FOR DEBUGGING.  You've been warned.
u64 IsoAlwaysFeedback = 0;

// This param is a fail-safe.  If anything goes wrong and we reboot,
// we recover to a fail-safe state.
u64 IsoAutoGenerateFeedback = 0;
u64 ISO_FEEDBACK_INTERVAL_US = 500;

// TODO: We are assuming that we don't need to do any VLAN tag
// ourselves
const u64 ISO_FEEDBACK_PACKET_SIZE = 64;
const u16 ISO_FEEDBACK_HEADER_SIZE = 14 + 20;
const u8 ISO_FEEDBACK_PACKET_TTL = 64;
u64 ISO_FEEDBACK_PACKET_IPPROTO = 143; // should be some unused protocol

// New parameters
u64 ISO_RL_UPDATE_INTERVAL_US = 200;
u64 ISO_BURST_FACTOR = 8;
u64 ISO_VQ_UPDATE_INTERVAL_US = 100;

struct iso_param iso_params[32] = {
  {"ISO_FALPHA", &ISO_FALPHA },
  {"ISO_MAX_TX_RATE", &ISO_MAX_TX_RATE },
  {"ISO_VQ_DRAIN_RATE_MBPS", &ISO_VQ_DRAIN_RATE_MBPS },
  {"ISO_MAX_BURST_TIME_US", &ISO_MAX_BURST_TIME_US },
  {"ISO_MIN_BURST_BYTES", &ISO_MIN_BURST_BYTES },
  {"ISO_RATEMEASURE_INTERVAL_US", &ISO_RATEMEASURE_INTERVAL_US },
  {"ISO_TOKENBUCKET_TIMEOUT_NS", &ISO_TOKENBUCKET_TIMEOUT_NS },
  {"ISO_TOKENBUCKET_MARK_THRESH_BYTES", &ISO_TOKENBUCKET_MARK_THRESH_BYTES },
  {"ISO_TOKENBUCKET_DROP_THRESH_BYTES", &ISO_TOKENBUCKET_DROP_THRESH_BYTES },
  {"ISO_VQ_MARK_THRESH_BYTES", &ISO_VQ_MARK_THRESH_BYTES },
  {"ISO_VQ_MAX_BYTES", &ISO_VQ_MAX_BYTES },
  {"ISO_RFAIR_INITIAL", &ISO_RFAIR_INITIAL },
  {"ISO_MIN_RFAIR", &ISO_MIN_RFAIR },
  {"ISO_RFAIR_INCREMENT", &ISO_RFAIR_INCREMENT },
  {"ISO_RFAIR_DECREASE_INTERVAL_US", &ISO_RFAIR_DECREASE_INTERVAL_US },
  {"ISO_RFAIR_INCREASE_INTERVAL_US", &ISO_RFAIR_INCREASE_INTERVAL_US },
  {"ISO_RFAIR_FEEDBACK_TIMEOUT", &ISO_RFAIR_FEEDBACK_TIMEOUT_US },
  {"ISO_RFAIR_FEEDBACK_TIMEOUT_DEFAULT_RATE", &ISO_RFAIR_FEEDBACK_TIMEOUT_DEFAULT_RATE },
  {"IsoGlobalEnabled", &IsoGlobalEnabled },
  {"IsoEnablePortClassMap", &IsoEnablePortClassMap },
  {"IsoAlwaysFeedback", &IsoAlwaysFeedback },
  {"IsoAutoGenerateFeedback", &IsoAutoGenerateFeedback },
  {"ISO_FEEDBACK_PACKET_IPPROTO", &ISO_FEEDBACK_PACKET_IPPROTO },
  {"ISO_FEEDBACK_INTERVAL_US", &ISO_FEEDBACK_INTERVAL_US },
  {"ISO_RL_UPDATE_INTERVAL_US", &ISO_RL_UPDATE_INTERVAL_US },
  {"ISO_BURST_FACTOR", &ISO_BURST_FACTOR },
  {"ISO_VQ_UPDATE_INTERVAL_US", &ISO_VQ_UPDATE_INTERVAL_US },
  {"", NULL},
};

int iso_num_params = 27;

/* Local Variables: */
/* indent-tabs-mode:t */
/* End: */

